using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliant(true)]
[assembly: AssemblyVersionAttribute("3.3.1.1")]
[assembly: AssemblyFileVersionAttribute("3.3.1.1")]
[assembly: AssemblyCopyrightAttribute("Copyright Jimmy Bogard 2008-2015")]
[assembly: AssemblyProductAttribute("AutoMapper")]
[assembly: AssemblyTrademarkAttribute("AutoMapper")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("95412947bb58204393701a36f5d48e88345e7bf9")]
